# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'github-actions' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/apps/*/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/packages/*/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'docker' # See documentation for possible values
    directory: '/apps/web/' # Location of package manifests
    schedule:
      interval: 'daily'

  - package-ecosystem: 'cargo' # See documentation for possible values
    directory: '/apps/gui/' # Location of package manifests
    schedule:
      interval: 'daily'
