on:
  release:
    types: [published]

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  release-web:
    runs-on: ubuntu-latest
    if: contains(github.event.release.tag_name, 'web')
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/web:latest
          context: .
          file: ./web.Dockerfile
          labels: |
            org.opencontainers.image.title=BeatForge Web
            org.opencontainers.image.description=The frontend for BeatForge
            org.opencontainers.image.url=https://beatforge.net

      - name: Deploy to Production
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker run -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --run-once
