on:
  push:
    branches:
      - main
    paths:
      - 'apps/web/**'
  pull_request:
    branches:
      - main
    paths:
      - 'apps/web/**'

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  release-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        if: github.event_name == 'push'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.event_name == 'push' }}
          tags: ghcr.io/${{ github.repository_owner }}/web:nightly
          file: web.Dockerfile
          context: .
          labels: |
            org.opencontainers.image.title=BeatForge Web
            org.opencontainers.image.description=The frontend for BeatForge
            org.opencontainers.image.url=https://beatforge.net

      - name: Deploy to Staging
        if: github.event_name == 'push'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker run -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --run-once
